In [1]:
import pandas as pd
import countries
from geopy.geocoders import Nominatim

In [5]:
file_path="C:/Users/veroj/OneDrive/Mis Documentos/POEI Data Engenieer/Projet POEI\Projet Meteo/Data/Disasters_Historique.csv"

In [7]:
# Reading csv file

data = pd.read_csv(file_path, sep=';')

data.head()

,disaster_num,date_event,date_event_fin,disaster_group,disaster_type,disaster_subtype,disaster_subsubtype,event_nom,ID_Continent,ISO_3,nom_continent,pays,location,disaster_magnitude,magnitude_scale,latitude,longitue,time,bassin,total_deaths
0,1970-0001-MAR,1970-01-22,1970-01-22,Hydrologique,Inondation,NaN,NaN,NaN,2.0,MAR,Africa,Morocco,Northern regions,NaN,Km2,NaN,NaN,00:00:00,NaN,11.0
1,1970-0002-PER,1970-01-01,1970-01-01,Hydrologique,Inondation,NaN,NaN,NaN,5.0,PER,South America,Peru,"(1) Lima, Sierra (2) Loreto department",NaN,Km2,NaN,NaN,00:00:00,NaN,3.0
2,1970-0004-PHL,1970-04-07,1970-04-07,Geophysique,Tremblement,Mouvement au sol,NaN,NaN,1.0,PHL,Asia,Philippines,Luzon,NaN,Richter,"15,791","121,63",00:00:00,NaN,14.0
3,1970-0010-CHN,1970-01-04,1970-01-04,Geophysique,Tremblement,Mouvement au sol,NaN,NaN,1.0,CHN,Asia,China,Yunnan province,7.0,Richter,"24,185","102,543",00:00:00,NaN,10000.0
4,1970-0013-ARG,1970-01-04,1970-01-04,Hydrologique,Inondation,NaN,NaN,NaN,5.0,ARG,South America,Argentina,Mendoza,NaN,Km2,NaN,NaN,00:00:00,NaN,36.0

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5704 entries, 0 to 5703
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   disaster_num         5704 non-null   object
 1   date_event           5704 non-null   object
 2   date_event_fin       5704 non-null   object
 3   disaster_group       5704 non-null   object
 4   disaster_type        5704 non-null   object
 5   disaster_subtype     4136 non-null   object
 6   disaster_subsubtype  380 non-null    object
 7   event_nom            1090 non-null   object
 8   ID_Continent         5506 non-null   float64
 9   ISO_3                5693 non-null   object
 10  nom_continent        5506 non-null   object
 11  pays                 5544 non-null   object
 12  location             4791 non-null   object
 13  disaster_magnitude   1708 non-null   float64
 14  magnitude_scale      5135 non-null   object
 15  latitude             611 non-null    object
 16  longitue             611 non-null    object
 17  time                 5625 non-null   object
 18  bassin               237 non-null    object
 19  total_deaths         3776 non-null   float64
dtypes: float64(3), object(17)
memory usage: 891.4+ KB

In [13]:
from dataclasses import replace

data["latitude"] = replace(data["latitude"], ',','.')
data["longitude"] = replace(data["longitude"], ',','.')
data["latitude"] = data.latitude.astype(float)
data["longitude"] = data.longitude.astype(float)

TypeError: descriptor 'replace' for 'str' objects doesn't apply to a 'Series' object

In [37]:
geolocator = Nominatim(user_agent="geoapiExercises")

def geo_name(lat, lon): 
        #location = geolocator.reverse(lat+","+lon)
        #address = location.raw['address']
        #country = address.get('country', '')
        country = countries.CountryChecker('TM_WORLD_BORDERS-0.3.shp')
        country.getCountry(countries.Point(lat, lon)).iso
        return country

#cc = countries.CountryChecker('TM_WORLD_BORDERS-0.3.shp')
#print cc.getCountry(countries.Point(49.7821, 3.5708)).iso

In [46]:
data.apply(geo_name, args = (7,8))

AttributeError: 'dict' object has no attribute 'apply'